(cl:defpackage enph353_gazebo-srv
  (:use )
  (:export
   "GETLEGALPLATES"
   "<GETLEGALPLATES-REQUEST>"
   "GETLEGALPLATES-REQUEST"
   "<GETLEGALPLATES-RESPONSE>"
   "GETLEGALPLATES-RESPONSE"
   "SUBMITPLATE"
   "<SUBMITPLATE-REQUEST>"
   "SUBMITPLATE-REQUEST"
   "<SUBMITPLATE-RESPONSE>"
   "SUBMITPLATE-RESPONSE"
  ))

