// Generated by gencpp from file enph353_gazebo/GetLegalPlatesRequest.msg
// DO NOT EDIT!


#ifndef ENPH353_GAZEBO_MESSAGE_GETLEGALPLATESREQUEST_H
#define ENPH353_GAZEBO_MESSAGE_GETLEGALPLATESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace enph353_gazebo
{
template <class ContainerAllocator>
struct GetLegalPlatesRequest_
{
  typedef GetLegalPlatesRequest_<ContainerAllocator> Type;

  GetLegalPlatesRequest_()
    : id()  {
    }
  GetLegalPlatesRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetLegalPlatesRequest_

typedef ::enph353_gazebo::GetLegalPlatesRequest_<std::allocator<void> > GetLegalPlatesRequest;

typedef boost::shared_ptr< ::enph353_gazebo::GetLegalPlatesRequest > GetLegalPlatesRequestPtr;
typedef boost::shared_ptr< ::enph353_gazebo::GetLegalPlatesRequest const> GetLegalPlatesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator1> & lhs, const ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator1> & lhs, const ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace enph353_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbfcda76036ebbe3d36caf7af80b260c";
  }

  static const char* value(const ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbfcda76036ebbe3ULL;
  static const uint64_t static_value2 = 0xd36caf7af80b260cULL;
};

template<class ContainerAllocator>
struct DataType< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "enph353_gazebo/GetLegalPlatesRequest";
  }

  static const char* value(const ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
;
  }

  static const char* value(const ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLegalPlatesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::enph353_gazebo::GetLegalPlatesRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENPH353_GAZEBO_MESSAGE_GETLEGALPLATESREQUEST_H
