// Generated by gencpp from file enph353_gazebo/GetLegalPlates.msg
// DO NOT EDIT!


#ifndef ENPH353_GAZEBO_MESSAGE_GETLEGALPLATES_H
#define ENPH353_GAZEBO_MESSAGE_GETLEGALPLATES_H

#include <ros/service_traits.h>


#include <enph353_gazebo/GetLegalPlatesRequest.h>
#include <enph353_gazebo/GetLegalPlatesResponse.h>


namespace enph353_gazebo
{

struct GetLegalPlates
{

typedef GetLegalPlatesRequest Request;
typedef GetLegalPlatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLegalPlates
} // namespace enph353_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::enph353_gazebo::GetLegalPlates > {
  static const char* value()
  {
    return "6ea3d197527ea87828940965246c0b06";
  }

  static const char* value(const ::enph353_gazebo::GetLegalPlates&) { return value(); }
};

template<>
struct DataType< ::enph353_gazebo::GetLegalPlates > {
  static const char* value()
  {
    return "enph353_gazebo/GetLegalPlates";
  }

  static const char* value(const ::enph353_gazebo::GetLegalPlates&) { return value(); }
};


// service_traits::MD5Sum< ::enph353_gazebo::GetLegalPlatesRequest> should match
// service_traits::MD5Sum< ::enph353_gazebo::GetLegalPlates >
template<>
struct MD5Sum< ::enph353_gazebo::GetLegalPlatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::enph353_gazebo::GetLegalPlates >::value();
  }
  static const char* value(const ::enph353_gazebo::GetLegalPlatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::enph353_gazebo::GetLegalPlatesRequest> should match
// service_traits::DataType< ::enph353_gazebo::GetLegalPlates >
template<>
struct DataType< ::enph353_gazebo::GetLegalPlatesRequest>
{
  static const char* value()
  {
    return DataType< ::enph353_gazebo::GetLegalPlates >::value();
  }
  static const char* value(const ::enph353_gazebo::GetLegalPlatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::enph353_gazebo::GetLegalPlatesResponse> should match
// service_traits::MD5Sum< ::enph353_gazebo::GetLegalPlates >
template<>
struct MD5Sum< ::enph353_gazebo::GetLegalPlatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::enph353_gazebo::GetLegalPlates >::value();
  }
  static const char* value(const ::enph353_gazebo::GetLegalPlatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::enph353_gazebo::GetLegalPlatesResponse> should match
// service_traits::DataType< ::enph353_gazebo::GetLegalPlates >
template<>
struct DataType< ::enph353_gazebo::GetLegalPlatesResponse>
{
  static const char* value()
  {
    return DataType< ::enph353_gazebo::GetLegalPlates >::value();
  }
  static const char* value(const ::enph353_gazebo::GetLegalPlatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ENPH353_GAZEBO_MESSAGE_GETLEGALPLATES_H
