// Generated by gencpp from file enph353_gazebo/SubmitPlateRequest.msg
// DO NOT EDIT!


#ifndef ENPH353_GAZEBO_MESSAGE_SUBMITPLATEREQUEST_H
#define ENPH353_GAZEBO_MESSAGE_SUBMITPLATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace enph353_gazebo
{
template <class ContainerAllocator>
struct SubmitPlateRequest_
{
  typedef SubmitPlateRequest_<ContainerAllocator> Type;

  SubmitPlateRequest_()
    : id()
    , plate()
    , location(0)
    , legal(false)
    , evidence()  {
    }
  SubmitPlateRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , plate(_alloc)
    , location(0)
    , legal(false)
    , evidence(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _plate_type;
  _plate_type plate;

   typedef int8_t _location_type;
  _location_type location;

   typedef uint8_t _legal_type;
  _legal_type legal;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _evidence_type;
  _evidence_type evidence;





  typedef boost::shared_ptr< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SubmitPlateRequest_

typedef ::enph353_gazebo::SubmitPlateRequest_<std::allocator<void> > SubmitPlateRequest;

typedef boost::shared_ptr< ::enph353_gazebo::SubmitPlateRequest > SubmitPlateRequestPtr;
typedef boost::shared_ptr< ::enph353_gazebo::SubmitPlateRequest const> SubmitPlateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator1> & lhs, const ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.plate == rhs.plate &&
    lhs.location == rhs.location &&
    lhs.legal == rhs.legal &&
    lhs.evidence == rhs.evidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator1> & lhs, const ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace enph353_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18d1e9687ce9e858dca913bb7abb560e";
  }

  static const char* value(const ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18d1e9687ce9e858ULL;
  static const uint64_t static_value2 = 0xdca913bb7abb560eULL;
};

template<class ContainerAllocator>
struct DataType< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "enph353_gazebo/SubmitPlateRequest";
  }

  static const char* value(const ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
"string plate\n"
"int8 location\n"
"bool legal\n"
"sensor_msgs/Image evidence\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.plate);
      stream.next(m.location);
      stream.next(m.legal);
      stream.next(m.evidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubmitPlateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::enph353_gazebo::SubmitPlateRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "plate: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.plate);
    s << indent << "location: ";
    Printer<int8_t>::stream(s, indent + "  ", v.location);
    s << indent << "legal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.legal);
    s << indent << "evidence: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.evidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENPH353_GAZEBO_MESSAGE_SUBMITPLATEREQUEST_H
