// Generated by gencpp from file enph353_gazebo/SubmitPlate.msg
// DO NOT EDIT!


#ifndef ENPH353_GAZEBO_MESSAGE_SUBMITPLATE_H
#define ENPH353_GAZEBO_MESSAGE_SUBMITPLATE_H

#include <ros/service_traits.h>


#include <enph353_gazebo/SubmitPlateRequest.h>
#include <enph353_gazebo/SubmitPlateResponse.h>


namespace enph353_gazebo
{

struct SubmitPlate
{

typedef SubmitPlateRequest Request;
typedef SubmitPlateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SubmitPlate
} // namespace enph353_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::enph353_gazebo::SubmitPlate > {
  static const char* value()
  {
    return "d7a5f82904bfc83df9f5ede6fec81ad1";
  }

  static const char* value(const ::enph353_gazebo::SubmitPlate&) { return value(); }
};

template<>
struct DataType< ::enph353_gazebo::SubmitPlate > {
  static const char* value()
  {
    return "enph353_gazebo/SubmitPlate";
  }

  static const char* value(const ::enph353_gazebo::SubmitPlate&) { return value(); }
};


// service_traits::MD5Sum< ::enph353_gazebo::SubmitPlateRequest> should match
// service_traits::MD5Sum< ::enph353_gazebo::SubmitPlate >
template<>
struct MD5Sum< ::enph353_gazebo::SubmitPlateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::enph353_gazebo::SubmitPlate >::value();
  }
  static const char* value(const ::enph353_gazebo::SubmitPlateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::enph353_gazebo::SubmitPlateRequest> should match
// service_traits::DataType< ::enph353_gazebo::SubmitPlate >
template<>
struct DataType< ::enph353_gazebo::SubmitPlateRequest>
{
  static const char* value()
  {
    return DataType< ::enph353_gazebo::SubmitPlate >::value();
  }
  static const char* value(const ::enph353_gazebo::SubmitPlateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::enph353_gazebo::SubmitPlateResponse> should match
// service_traits::MD5Sum< ::enph353_gazebo::SubmitPlate >
template<>
struct MD5Sum< ::enph353_gazebo::SubmitPlateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::enph353_gazebo::SubmitPlate >::value();
  }
  static const char* value(const ::enph353_gazebo::SubmitPlateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::enph353_gazebo::SubmitPlateResponse> should match
// service_traits::DataType< ::enph353_gazebo::SubmitPlate >
template<>
struct DataType< ::enph353_gazebo::SubmitPlateResponse>
{
  static const char* value()
  {
    return DataType< ::enph353_gazebo::SubmitPlate >::value();
  }
  static const char* value(const ::enph353_gazebo::SubmitPlateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ENPH353_GAZEBO_MESSAGE_SUBMITPLATE_H
