<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="vehicle">

  <xacro:property name="base_width" value="0.07"/>
  <xacro:property name="base_height" value="0.07"/>
  <xacro:property name="base_len" value="0.18"/>
  <xacro:property name="base_mass" value="0.9"/>
  <xacro:property name="mesh_file"/>

  <xacro:include filename="$(find enph353_npcs)/agents/vehicle/urdf/macros.xacro" />
<!-- Chassis -->
  <link name="base_link">
    <xacro:box_inertia m="${base_mass}" w="${base_width}" h="${base_height}" d="${base_len}"/>
    <visual name="visual">
      <origin xyz="0 0 ${-base_height/2}" rpy="0 0 -1.57" />
      <geometry>
        <mesh filename="$(arg mesh_file)" scale="0.045 0.045 0.045" />
      </geometry>
    </visual>
    <collision name="collision">
      <geometry>
        <box size="${base_len} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>


  <gazebo>
    <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometryRate>20.0</odometryRate>
      <robotBaseFrame>base_link</robotBaseFrame>
    </plugin>
  </gazebo>
</robot>